"""empty message

Revision ID: 1c545fee7484
Revises: 5813c1b9304f
Create Date: 2015-04-15 23:57:22.997160

"""

# revision identifiers, used by Alembic.
revision = '1c545fee7484'
down_revision = '5813c1b9304f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
