"""empty message

Revision ID: 1ea87c888fac
Revises: 1c545fee7484
Create Date: 2015-04-15 23:58:22.717372

"""

# revision identifiers, used by Alembic.
revision = '1ea87c888fac'
down_revision = '1c545fee7484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
