"""empty message

Revision ID: 2d8f9d374aa
Revises: 59c967517f3
Create Date: 2015-01-23 00:03:14.924401

"""

# revision identifiers, used by Alembic.
revision = '2d8f9d374aa'
down_revision = '59c967517f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playermatch_player_id'), 'playermatch', ['player_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playermatch_player_id'), table_name='playermatch')
    ### end Alembic commands ###
