"""empty message

Revision ID: 312b5d37874b
Revises: 3928b33f346b
Create Date: 2015-04-16 00:02:18.908710

"""

# revision identifiers, used by Alembic.
revision = '312b5d37874b'
down_revision = '3928b33f346b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
