"""empty message

Revision ID: 3928b33f346b
Revises: 1ea87c888fac
Create Date: 2015-04-16 00:00:53.993394

"""

# revision identifiers, used by Alembic.
revision = '3928b33f346b'
down_revision = '1ea87c888fac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
