"""empty message

Revision ID: 3f0e2e913bf5
Revises: 544fa414515c
Create Date: 2015-04-12 16:18:11.397154

"""

# revision identifiers, used by Alembic.
revision = '3f0e2e913bf5'
down_revision = '544fa414515c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
