"""empty message

Revision ID: 544fa414515c
Revises: 2d8f9d374aa
Create Date: 2015-04-01 11:08:11.568549

"""

# revision identifiers, used by Alembic.
revision = '544fa414515c'
down_revision = '2d8f9d374aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playermatch_match_id'), 'playermatch', ['match_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playermatch_match_id'), table_name='playermatch')
    ### end Alembic commands ###
